name: 'Infomaniak Uploader'
description: 'Uploads files securely through the Infomaniak FTP Manager'
author: 'Roger K.'
inputs:
  ftpServer:
    description: 'domain name of the Infomaniak-hosted FTP server'
    required: true
  ftpUser:
    description: 'user name for FTP access'
    required: true
  ftpPassword:
    description: 'password for FTP access'
    required: true
  localRoot:
    description: 'path to the local folder (on the agent) to upload from'
    required: true
  remoteRoot:
    description: 'path to the remote folder (on the FTP server) to upload to'
    required: true
    default: '/'
  cleanupDirs:
    description: 'directories to clean up (remove old files) after upload'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: upload-cloud
  color: blue
